[job]
description = "Wan2.1 T2V Training debug"
dump_folder = "./outputs/wan2.1_t2v_debug_vae_t5_load2"
custom_config_module = "torchtitan.experiments.wan.job_config"

[model]
name = "wan"
flavor = "wan2.1_t2v_debug"

[metrics]
log_freq = 1
disable_color_printing = true
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = false

[training]
local_batch_size = 2
max_norm = 1.0
mixed_precision_param = "bfloat16"
steps = 10
enable_cpu_offload = false
seed = 0
deterministic = true

# dataset = "/root/zirui/data/example_video_dataset/metadata.jsonl"
# dataset = "example_video"
dataset = "vidgen-1m"

[encoder]
# t5_encoder = "google/t5-v1_1-xxl"
# clip_encoder = "openai/clip-vit-large-patch14"
# max_t5_encoding_len = 256
t5_checkpoint_path = "/root/zirui/models/Wan2.1-T2V-14B/models_t5_umt5-xxl-enc-bf16.pth"
vae_checkpoint_path = "/root/zirui/models/Wan2.1-T2V-14B/Wan2.1_VAE.pth"
vae_type = "wan_video_vae"

[optimizer]
name = "AdamW"
lr = 5e-6
eps = 1e-8

[lr_scheduler]
decay_type = "cosine"
warmup_steps = 100

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1    # Full Shard
tensor_parallel_degree = 1
pipeline_parallel_degree = 1

[activation_checkpoint]
mode = "none"

[checkpoint]
enable = false
interval = 30
export_dtype = "float32"

[validation]
enable = false
