#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/config_common.sh"

export NNODES=1
export DP_REPLICATE=1
export LOCAL_BATCH_SIZE=32
export GRADIENT_ACCUMULATION_STEPS=4
export GLOBAL_BATCH_SIZE=1024
export LR=0.00025
export WARMUP_STEPS=800
export GRADIENT_CHECKPOINTING_RATIO=0
export TORCH_COMPILE_MODE=${TORCH_COMPILE_MODE:-}
export FLUX_FP8_GEMM_BACKEND=${FLUX_FP8_GEMM_BACKEND:-hipblaslt_fixed}
export FLUX_FP8_ALL_GATHER=${FLUX_FP8_ALL_GATHER:-1}
export TORCHINDUCTOR_BENCHMARK_FUSION=1
export PRIMUS_FLUX_AITER_ATOMIC_FP32=0
export PRIMUS_FLUX_REUSE_FP8_INPUT=1

# Qualified MI355X single-node scheduling and communication defaults.
export FSDP2_FORCE_SUM=${FSDP2_FORCE_SUM:-1}
export HSA_ENABLE_SDMA=${HSA_ENABLE_SDMA:-1}
export GPU_MAX_HW_QUEUES=${GPU_MAX_HW_QUEUES:-2}
export TORCH_NCCL_HIGH_PRIORITY=${TORCH_NCCL_HIGH_PRIORITY:-1}
export NCCL_CHECKS_DISABLE=${NCCL_CHECKS_DISABLE:-1}
export NCCL_P2P_NET_CHUNKSIZE=${NCCL_P2P_NET_CHUNKSIZE:-524288}
export TORCH_NCCL_USE_TENSOR_REGISTER_ALLOCATOR_HOOK=${TORCH_NCCL_USE_TENSOR_REGISTER_ALLOCATOR_HOOK:-0}
