#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/config_common.sh"

export NNODES=4
export DP_REPLICATE=4
export LOCAL_BATCH_SIZE=32
export GRADIENT_ACCUMULATION_STEPS=1
export GLOBAL_BATCH_SIZE=1024
export LR=0.00025
export WARMUP_STEPS=800
export GRADIENT_CHECKPOINTING_RATIO=0
export TORCH_COMPILE_MODE=${TORCH_COMPILE_MODE:-}
if [[ -n "${TORCHINDUCTOR_CACHE_SEED:-}" && -z "$TORCH_COMPILE_MODE" ]]; then
    export TORCH_COMPILE_MODE=max-autotune-no-cudagraphs
fi
export FLUX_FP8_GEMM_BACKEND=selective_flydsl
export TORCHINDUCTOR_BENCHMARK_FUSION=1
export PRIMUS_FLUX_AITER_ATOMIC_FP32=0
export PRIMUS_FLUX_REUSE_FP8_INPUT=1

# Match the validated MI355X scheduling environment before Python starts.
export HSA_ENABLE_SDMA=1
export HSA_NO_SCRATCH_RECLAIM=1
export GPU_MAX_HW_QUEUES=2
export CUDA_DEVICE_MAX_CONNECTIONS=1
export TORCH_NCCL_HIGH_PRIORITY=1
export NCCL_CHECKS_DISABLE=1
export NCCL_PXN_DISABLE=1
export NCCL_P2P_NET_CHUNKSIZE=524288
export TORCH_NCCL_USE_TENSOR_REGISTER_ALLOCATOR_HOOK=0
