#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/config_common.sh"

export NNODES=4
export DP_REPLICATE=${DP_REPLICATE:-4}
export LOCAL_BATCH_SIZE=32
export GRADIENT_ACCUMULATION_STEPS=1
export GLOBAL_BATCH_SIZE=1024
export LR=0.00025
export WARMUP_STEPS=800
export GRADIENT_CHECKPOINTING_RATIO=0
export TORCH_COMPILE_MODE=${TORCH_COMPILE_MODE:-}
if [[ -n "${TORCHINDUCTOR_CACHE_SEED:-}" && -z "$TORCH_COMPILE_MODE" ]]; then
    export TORCH_COMPILE_MODE=max-autotune-no-cudagraphs
fi
export FLUX_FP8_GEMM_BACKEND=selective_flydsl
export TORCHINDUCTOR_BENCHMARK_FUSION=1
export PRIMUS_FLUX_AITER_ATOMIC_FP32=0
export PRIMUS_FLUX_REUSE_FP8_INPUT=1

# Qualified MI355X scheduling and communication defaults.
export HSA_ENABLE_SDMA=${HSA_ENABLE_SDMA:-1}
export GPU_MAX_HW_QUEUES=${GPU_MAX_HW_QUEUES:-2}
export TORCH_NCCL_HIGH_PRIORITY=${TORCH_NCCL_HIGH_PRIORITY:-1}
export NCCL_CHECKS_DISABLE=${NCCL_CHECKS_DISABLE:-1}
export NCCL_P2P_NET_CHUNKSIZE=${NCCL_P2P_NET_CHUNKSIZE:-524288}
export TORCH_NCCL_USE_TENSOR_REGISTER_ALLOCATOR_HOOK=${TORCH_NCCL_USE_TENSOR_REGISTER_ALLOCATOR_HOOK:-0}

# Do not inherit unrelated host NCCL tuning into the qualified Crusoe recipe.
export NCCL_IB_GID_INDEX=${FLUX_NCCL_IB_GID_INDEX:-1}
export NCCL_IB_TC=${FLUX_NCCL_IB_TC:-104}
export NCCL_IB_FIFO_TC=${FLUX_NCCL_IB_FIFO_TC:-192}
export NCCL_IB_USE_INLINE=${FLUX_NCCL_IB_USE_INLINE:-1}
export NCCL_IB_QPS_PER_CONNECTION=${FLUX_NCCL_IB_QPS_PER_CONNECTION:-1}
export NCCL_NET_PLUGIN=${FLUX_NCCL_NET_PLUGIN:-librccl-anp.so}
export NCCL_MAX_P2P_CHANNELS=${FLUX_NCCL_MAX_P2P_CHANNELS:-56}
export NCCL_GDR_FLUSH_DISABLE=${FLUX_NCCL_GDR_FLUSH_DISABLE:-1}
export NCCL_DMABUF_ENABLE=${FLUX_NCCL_DMABUF_ENABLE:-1}
export NCCL_NET_GDR_LEVEL=${FLUX_NCCL_NET_GDR_LEVEL:-SYS}
export NCCL_NET_GDR_READ=${FLUX_NCCL_NET_GDR_READ:-1}
export NCCL_PXN_DISABLE=${FLUX_NCCL_PXN_DISABLE:-1}
export NCCL_IGNORE_CPU_AFFINITY=${FLUX_NCCL_IGNORE_CPU_AFFINITY:-1}
export NCCL_CROSS_NIC=${FLUX_NCCL_CROSS_NIC:-0}
export NET_OPTIONAL_RECV_COMPLETION=${FLUX_NET_OPTIONAL_RECV_COMPLETION:-1}
