#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)

: "${SLURM_JOB_ID:?Run inside a Slurm/Spur allocation}"
: "${SLURM_NNODES:?Missing SLURM_NNODES}"
: "${DATA_ROOT:?Set DATA_ROOT}"
: "${OUTPUT_ROOT:?Set OUTPUT_ROOT}"

export FLUX_CONFIG=${FLUX_CONFIG:-config_4n_gbs1024.sh}
[[ -f "$SCRIPT_DIR/$FLUX_CONFIG" ]] || { echo "Unknown FLUX_CONFIG: $FLUX_CONFIG" >&2; exit 2; }
source "$SCRIPT_DIR/$FLUX_CONFIG"
[[ "$NNODES" == "$SLURM_NNODES" ]] || {
    echo "$FLUX_CONFIG requires $NNODES nodes; allocation has $SLURM_NNODES" >&2
    exit 2
}
if [[ -z "${MASTER_ADDR:-}" ]]; then
    if [[ "$NNODES" == "1" ]]; then
        MASTER_ADDR=${SLURMD_NODENAME:-$SLURM_JOB_NODELIST}
    elif command -v scontrol >/dev/null; then
        MASTER_ADDR=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n1)
    else
        MASTER_ADDR=${SPUR_PEER_NODES:?Set MASTER_ADDR}
        MASTER_ADDR=${MASTER_ADDR%%,*}
        MASTER_ADDR=${MASTER_ADDR%%:*}
    fi
fi
export MASTER_ADDR MASTER_PORT=${MASTER_PORT:-29500}

srun_args=(--nodes="$NNODES" --ntasks="$NNODES" --ntasks-per-node=1)
command -v spur >/dev/null && srun_args+=(--jobid="$SLURM_JOB_ID" --overlap)

forward_vars=(
    FLUX_CONFIG DOCKER_IMAGE CONFIG GPUS_PER_NODE DP_REPLICATE
    DATASET_PATH EVAL_DATASET_PATH EMPTY_ENCODINGS_PATH OUTPUT_DIR MLLOG_OUTPUT_FILE
    MLLOG_SUBMISSION_DIVISION MLLOG_SUBMISSION_ORG MLLOG_SUBMISSION_PLATFORM
    MLLOG_SUBMISSION_POC_NAME MLLOG_SUBMISSION_POC_EMAIL MLLOG_SUBMISSION_STATUS
    FLUX_FLOAT8_RECIPE FLUX_FP8_GEMM_BACKEND FLUX_MXFP4_RECIPE
    FLUX_MXFP4_FORWARD_PRECISION FLUX_MXFP4_FORWARD_HADAMARD
    FLUX_MXFP4_BF16_FORWARD_SCOPE FLUX_MXFP4_SELECTIVE_FORWARD_SCOPE
    FLUX_MXFP4_ACTIVATION_RESIDUAL FLUX_MXFP4_ACTIVATION_RESIDUAL_DTYPE
    FLUX_MXFP4_EVAL_PRECISION FLUX_MXFP4_GRADIENT_SR
    FLUX_MXFP4_CAPTURE_STEPS FLUX_MXFP4_CAPTURE_MODULES FLUX_MXFP4_CAPTURE_DIR
    FLUX_MXFP4_BF16_FORWARD_SWITCH_STEP ATTENTION_BACKEND LOCAL_BATCH_SIZE EVAL_BATCH_SIZE
    DATALOADER_NUM_WORKERS EVAL_DATALOADER_NUM_WORKERS EVAL_DATALOADER_PREFETCH_FACTOR
    GRADIENT_ACCUMULATION_STEPS GLOBAL_BATCH_SIZE MAX_STEPS LR WARMUP_STEPS
    GRADIENT_CHECKPOINTING GRADIENT_CHECKPOINTING_RATIO COMPILE_TRANSFORMER_BLOCKS COMPILE_STRATEGY
    COMPILE_BACKEND COMPILE_FULLGRAPH COMPILE_DYNAMIC COMPILE_OUTPUT_HEAD TORCH_COMPILE_MODE
    FSDP2_RESHARD_AFTER_FORWARD FSDP2_REDUCE_DTYPE FLUX_FP8_ALL_GATHER FLUX_PERFORMANCE_MODE
    PROFILE PROFILE_RANK PROFILE_WAIT_STEPS PROFILE_WARMUP_STEPS PROFILE_ACTIVE_STEPS
    PROFILE_OUTPUT_DIR PROFILE_WITH_STACK PIN_FLUX_T5_STACK SAVE_STEPS SAVE_STRATEGY CHECKPOINT_KEEP_LATEST RESUME_FROM_CHECKPOINT
    MLPERF_ENABLE MLPERF_WARMUP_TRAIN_STEPS MLPERF_WARMUP_VALIDATION_STEPS
    MLPERF_CLEAR_CACHES TARGET_ACCURACY VAL_CHECK_INTERVAL SEED LOG_FREQ ENABLE_WANDB_LOGGER
    TORCHINDUCTOR_CACHE_DIR TORCHINDUCTOR_CACHE_SEED TORCHINDUCTOR_CACHE_EXPORT
    PRIMUS_TURBO_GEMM_BACKEND PRIMUS_TURBO_AUTO_TUNE
)
env_args=(DATA_ROOT="$DATA_ROOT" OUTPUT_ROOT="$OUTPUT_ROOT" NNODES="$NNODES" MASTER_ADDR="$MASTER_ADDR" MASTER_PORT="$MASTER_PORT")
for name in "${forward_vars[@]}"; do
    [[ -v "$name" ]] && env_args+=("$name=${!name}")
done

exec srun "${srun_args[@]}" env "${env_args[@]}" bash "$SCRIPT_DIR/run_with_docker.sh"
